# Generated by Django 6.0 on 2025-12-24 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('greeting_message', models.CharField(blank=True, default='Hi! How can I help you?', max_length=280)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='agents/icons/%Y/%m/')),
                ('title_bar_color', models.CharField(default='#0F172A', max_length=16)),
                ('window_bg_color', models.CharField(default='#020617', max_length=16)),
                ('bot_bubble_color', models.CharField(default='#0EA5A4', max_length=16)),
                ('user_bubble_color', models.CharField(default='#334155', max_length=16)),
                ('text_color', models.CharField(default='#E2E8F0', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
