# Generated by Django 6.0 on 2025-12-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('sources', '0006_tag_datasource_tags_datasourcepage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('website_guidance', 'Website Guidance'), ('contact_data', 'Contact Data'), ('support_faq', 'Support FAQ'), ('document_referral', 'Document Referral')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='agents.agent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_links', to='sources.datasource')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'role'], name='agents_agen_agent_i_bda107_idx'), models.Index(fields=['source', 'role'], name='agents_agen_source__8b2a8e_idx')],
                'unique_together': {('agent', 'source', 'role')},
            },
        ),
    ]
