# Generated by Django 6.0 on 2025-12-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_conversation_leadcapture_documentaccesstoken_message_and_more'),
        ('sources', '0006_tag_datasource_tags_datasourcepage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentindexitem',
            name='tags_text',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='agentindexitem',
            index=models.Index(fields=['source'], name='agents_agen_source__a73e16_idx'),
        ),
        migrations.AddIndex(
            model_name='agentindexitem',
            index=models.Index(fields=['page'], name='agents_agen_page_id_0be1a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentindexitem',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'page')), fields=('agent', 'role', 'page'), name='uniq_agent_role_page_item'),
        ),
        migrations.AddConstraint(
            model_name='agentindexitem',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'source')), fields=('agent', 'role', 'source'), name='uniq_agent_role_source_item'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('agent', 'session_id'), name='uniq_convo_agent_session'),
        ),
    ]
