# Generated by Django 6.0 on 2025-12-22 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source_type', models.CharField(choices=[('website', 'Website'), ('document', 'Document'), ('sheet', 'Sheet'), ('custom', 'Custom')], max_length=20)),
                ('domain_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('total_pages', models.IntegerField(default=0)),
                ('selected_pages', models.IntegerField(default=0)),
                ('processed_pages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSourcePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('product', 'Product'), ('info', 'Info')], default='info', max_length=20)),
                ('selected', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sources.datasource')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'category', 'selected'], name='sources_dat_source__84f3ed_idx'), models.Index(fields=['source', 'status'], name='sources_dat_source__e7aff8_idx')],
                'unique_together': {('source', 'url')},
            },
        ),
    ]
