# Generated by Django 6.0 on 2025-12-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sources/uploads/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
