# Generated by Django 6.0 on 2025-12-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_datasource_file_datasource_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='source_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datasource',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
