# Generated by Django 6.0 on 2025-12-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_datasource_source_context_datasource_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcepage',
            name='preview',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
