# Generated by Django 6.0 on 2025-12-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_datasourcepage_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='custom_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
