# Generated by Django 6.0 on 2025-12-23 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_datasource_custom_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='data_sources', to='sources.tag'),
        ),
        migrations.AddField(
            model_name='datasourcepage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='sources.tag'),
        ),
    ]
